name: Echo
on: 
  pull_request:
    branches: [ main ]
  push: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Echo name
        run: echo The username is 1
