name: Echo3
on:
  workflow_dispatch:
    inputs:
      trigger_next:
        description: 'Whether to run the subsequent workflows after triggering this one manully.'
  repository_dispatch:
    types: [echo3]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Echo name
        run: echo The username is  3 ${{ github.event.client_payload.name }}
