name: Shopify Lighthouse CI
on:
  pull_request:
    branches: [ main ]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@1.0
      with:
        app_id: ${{ secrets.SHOP_APP_ID }}
        app_password: ${{ secrets.SHOP_APP_PASSWORD }}
        store: ${{ secrets.SHOP_STORE }}
        password: ${{ secrets.SHOP_PASSWORD }}
        lhci_github_app_token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install && npm install -g @lhci/cli@0.6.x
      - run: npm run build
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
