name: Shopify Lighthouse CI
on:
  workflow_dispatch:
    inputs:
      trigger_next:
        description: 'Whether to run the subsequent workflows after triggering this one manully.'
  repository_dispatch:
    types: [lighthouse]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@1.0
      with:
        app_id: ${{ secrets.SHOP_APP_ID }}
        app_password: ${{ secrets.SHOP_APP_PASSWORD }}
        store: ${{ secrets.SHOP_STORE }}
        password: ${{ secrets.SHOP_PASSWORD }}
