name: Auto minified JS, CSS and Deploy Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
jobs:
  reduce_tailwind:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
          cache: 'npm'
      - run: npm install
      - run: npm test

                   

      # - name: Auto committing minified files
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "Github Action: Auto Minified JS and CSS files"
  
