name: Auto minified JS, CSS and Deploy Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
jobs:
  check_change:
    runs-on: ubuntu-latest
    outputs: 
      is_changed: ${{steps.changed-files.outputs.any_changed}}
      list_files: ${{steps.changed-files.outputs.all_modified_files}}
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          files: 
             assets/theme.js
             assets/theme.css
  minified:
      runs-on: ubuntu-latest
      needs: check_change
      if: github.event.action == 'opened' || needs.check_change.outputs.is_changed == 'true'
      steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Auto Minify JS
        if: github.event.action == 'opened' || contains(needs.check_change.outputs.list_files, 'theme.js')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "assets/theme.js"

      - name: Auto Minify Css
        if: github.event.action == 'opened' || contains(needs.check_change.outputs.list_files, 'theme.css')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "assets/theme.css"

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"

  reduce_tailwind:
      name: 'Reduce tailwind'
      needs: minified
      if: ${{ always() }}
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - name: install npm
        continue-on-error: true
        run: |
          cd tailwind
          npm install

      - name: Reduce tailwind css
        continue-on-error: true
        run: |
          cd tailwind
          npm run prod
      
      - name: Auto committing tailwind file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto reduce tailwind css"

  deploy_preview:
    name: 'Deploy Preview'
    needs: reduce_tailwind
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install shopify-cli
        run: 
          sudo gem install shopify-cli -v ${{ secrets.DP_SHOPIFY_CLI_VERSION }}
          
        #Secret environment variable that turns shopify CLI into CI mode that accepts environment credentials
      - name: Set env 
        run: |
          echo "CI=1" >> $GITHUB_ENV
          echo "SHOPIFY_SHOP=${{secrets.DP_SHOPIFY_STORE}}" >> $GITHUB_ENV
          echo "SHOPIFY_PASSWORD=${{secrets.DP_SHOPIFY_APP_PW}}" >> $GITHUB_ENV
          
      - name: Logged into store as staff 
        run: |
          shopify login [--store ${{env.SHOPIFY_SHOP}}]
      - name: Check theme PR
        continue-on-error: true
        id: check_theme
        run: |
          echo 'PR_THEME<<EOF' >> $GITHUB_ENV
          shopify theme pull -t PR#${{github.event.pull_request.number}} -x /  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Create new theme unpublished
        id: create_theme
        if: steps.check_theme.outcome != 'success'
        continue-on-error: true
        timeout-minutes: 3
        run: |
          shopify theme push --unpublished --json -t PR#${{github.event.pull_request.number}}
          echo 'PR_THEME<<EOF' >> $GITHUB_ENV
          shopify theme pull -t PR#${{github.event.pull_request.number}} -x /  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Get PR_THEME_ID
        if: steps.check_theme.outcome == 'success' || steps.create_theme.outcome == 'success'
        run: |
          export PR_THEME="${{env.PR_THEME}}"
          export A=$(awk -F'#' '{print $3}' <<< "$PR_THEME")
          export B=$(awk -F'\)' '{print $1}' <<< "$A")
          
          echo 'PR_THEME_ID<<EOF' >> $GITHUB_ENV
          echo $B >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Update theme 
        if: steps.check_theme.outcome == 'success'
        run: shopify theme push -t ${{env.PR_THEME_ID}}

      - name: Delete preview if merge PR
        if: github.event.action == 'closed'
        run: shopify theme delete ${{env.PR_THEME_ID}} -f
                    
      - name: Comment PR
        if: github.event.action != 'closed' && steps.create_theme.outcome != 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Deployed successfully to https://shen-yun-shop-dev.myshopify.com/?preview_theme_id=${{env.PR_THEME_ID}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default

      - name: Comment PR
        if: github.event.action != 'closed' && steps.create_theme.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            Unable to create a new theme. The limit of 20 themes has been reached.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
