name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Minifi-css-js
        uses: devatherock/minify-js@v1.0.3
        with:
          directory: "./theme.css"
