name: Auto minified JS, CSS and Deploy Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
jobs:
  deploy_preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install shopify-cli
        run: 
          sudo gem install shopify-cli -v 2.10.0
          
        #Secret environment variable that turns shopify CLI into CI mode that accepts environment credentials
      - name: Set env 
        run: |
          echo "CI=1" >> $GITHUB_ENV
          echo "SHOPIFY_SHOP=${{secrets.DP_SHOPIFY_STORE}}" >> $GITHUB_ENV
          echo "SHOPIFY_PASSWORD=${{secrets.DP_SHOPIFY_APP_PW}}" >> $GITHUB_ENV
          echo $CI
          echo $SHOPIFY_SHOP
          echo $SHOPIFY_PASSWORD
          
      # - name: Logged into store as staff 
      #   run: |
      #     shopify login [--store ${{env.SHOPIFY_SHOP}}]
          
      # - name: Create new theme unpublished
      #   if: github.event.action == 'opened' || github.event.action == 'reopened'
      #   run: |
      #     echo 'PR_THEME<<EOF' >> $GITHUB_ENV
      #     shopify theme push --unpublished --json -t PR#${{github.event.pull_request.number}}  >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV
          
      # - name: Get PR_THEME_ID
      #   if: github.event.action == 'opened' || github.event.action == 'reopened'
      #   run: |
      #     export PRTHEME="${{env.PR_THEME}}"
      #     export A=$(awk -F'preview_theme_id=' '{print $2}' <<< "$PRTHEME")
      #     export B=$(awk -F'}' '{print $1}' <<< "$A")
          
      #     echo 'PR_THEME_ID<<EOF' >> $GITHUB_ENV
      #     echo $B >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV
          
      # - name: Pull theme PR
      #   if: github.event.action == 'synchronize' || github.event.action == 'closed'
      #   run: |
      #     echo 'PR_THEME<<EOF' >> $GITHUB_ENV
      #     shopify theme pull -t PR#${{github.event.pull_request.number}} -x /  >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV
          
      # - name: Get PR_THEME_ID
      #   if: github.event.action == 'synchronize' || github.event.action == 'closed'
      #   run: |
      #     export PRTHEME="${{env.PR_THEME}}"
      #     export A=$(awk -F'#' '{print $3}' <<< "$PRTHEME")
      #     export B=$(awk -F'\)' '{print $1}' <<< "$A")
          
      #     echo 'PR_THEME_ID<<EOF' >> $GITHUB_ENV
      #     echo $B >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV
      
      # - name: Update theme 
      #   if: github.event.action == 'synchronize'
      #   run: shopify theme push -t ${{env.PR_THEME_ID}}  

      # - name: Delete preview if merge PR
      #   if: github.event.action == 'closed'
      #   run: shopify theme delete ${{env.PR_THEME_ID}} -f
                    
      # - name: Comment PR
      #   if: github.event.action != 'closed'
      #   uses: mshick/add-pr-comment@v1
      #   with:
      #     message: |
      #       Deployed successfully to https://shen-yun-shop-dev.myshopify.com/?preview_theme_id=${{env.PR_THEME_ID}}
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
      #     allow-repeats: false # This is the default