name: Auto minified JS and CSS
on :  push
jobs:
  check_change:
    runs-on: ubuntu-latest
    outputs: 
      list_files: ${{steps.files.outputs.all}}
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - run:
          echo ${{ github.event[0].commit }}
      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        
#         uses: tj-actions/changed-files@v11.9
#         with:
#           files: 
#              theme.js
#              theme.css
        
  minified:
      runs-on: ubuntu-latest
      needs: check_change
      steps:
      - uses: actions/checkout@v2 
      
      - name: Auto Minify JS
        if: contains(needs.check_change.outputs.list_files, 'theme.js')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "theme.js"
          
      - name: Auto Minify Css
        if: contains(needs.check_change.outputs.list_files, 'theme.css')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "theme.css"

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
