name: Auto minified JS, CSS and Deploy Preview
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:

 deploy_preview:
    runs-on: ubuntu-latest
    name: 'Deploy Preview'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install shopify-cli
        run: 
          sudo gem install shopify-cli
      - name: Set Env
        run: |
          echo "CI=1" >> $GITHUB_ENV
          echo "SHOPIFY_SHOP=${{secrets.DP_SHOPIFY_STORE}}" >> $GITHUB_ENV
          echo "SHOPIFY_PASSWORD=${{secrets.DP_SHOPIFY_APP_PW}}" >> $GITHUB_ENV
          
      - name: Logged into store as staff 
        run: |
          shopify login [--store ${{env.SHOPIFY_SHOP}}]
          shopify theme push --unpublished --json -t ${{github.event.pull_request.number}}

      - name: Pull code
        run: |
          echo 'PR_THERME<<EOF' >> $GITHUB_ENV
          shopify theme pull -t ${{github.event.pull_request.number}} -n  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create and update preview  
        if: github.event.action == 'closed'
        run: shopify theme push --unpublished --json -t ${{github.event.pull_request.number}}
       # run: |
         # echo 'PR_THERME<<EOF' >> $GITHUB_ENV
         # shopify theme serve  >> $GITHUB_ENV
         # echo 'EOF' >> $GITHUB_ENV

      - name: Get PR ID
        run: echo ${{github.event.pull_request.id}}
      #   run: |
      #     export A=$(awk -F'preview_theme_id=' '{print $2}' <<< "${{env.PR_THERME}}")
      #     export B=$(awk -F'}' '{print $1}' <<< "$A")
          
      #     echo 'PR_THERME_ID<<EOF' >> $GITHUB_ENV
      #     echo $B >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV
        

      # - name: Delete preview 
      #   if: github.event.action == 'closed'
      #   run: shopify theme delete {${{github.event.pull_request.id}}} -f -d
                    
      # - name: Comment PR
      #   uses: mshick/add-pr-comment@v1
      #   with:
      #     message: |
      #       Deployed successfully to ${{secrets.DP_SHOPIFY_STORE}}/?preview_theme_id=${{env.PR_THERME_ID}}
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
      #     allow-repeats: false # This is the default