name: Auto minified JS and CSS
on :  workflow_dispatch:
    inputs:
      trigger_next:
        description: 'Whether to run the subsequent workflows after triggering this one manully.'
        required: false
        default: false
  repository_dispatch:
    types: [minified JS and CSS]
jobs:
  check_change:
    runs-on: ubuntu-latest
    outputs: 
      is_changed: ${{steps.changed-files.outputs.any_changed}}
      list_files: ${{steps.changed-files.outputs.all_modified_files}}
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          files: 
             asss/theme.js
             asss/theme.css
  minified:
      runs-on: ubuntu-latest
      needs: check_change
      if: needs.check_change.outputs.is_changed == 'true'
      steps:
      - uses: actions/checkout@v2 
      
      - name: Auto Minify JS
        if: contains(needs.check_change.outputs.list_files, 'theme.js')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "theme.js"
          
      - name: Auto Minify Css
        if: contains(needs.check_change.outputs.list_files, 'theme.css')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "theme.css"

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
