name: Auto minified JS and CSS
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify JS
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: ['./theme.css', './theme.js']
          
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
