name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Minifi
        uses: devatherock/minify-js@v1.0.3
        with:
          directory: "./theme.css"
          output: ""
          add_suffix: ""
