name: Auto minified JS, CSS and Deploy Preview
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  check_change:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' && github.event.action != 'opened' 
    outputs: 
      is_changed: ${{steps.changed-files.outputs.any_changed}}
      list_files: ${{steps.changed-files.outputs.all_modified_files}}
    steps:
      - uses: actions/checkout@v2 
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9
        with:
          files: 
             assets/theme.js
             assets/theme.css
  minified:
      runs-on: ubuntu-latest
      needs: check_change
      if: github.event.action == 'opened' || (github.event.action != 'closed' && needs.check_change.outputs.is_changed == 'true' )
      steps:
      - uses: actions/checkout@v2 
      
      - name: Auto Minify JS
        if: contains(needs.check_change.outputs.list_files, 'theme.js')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "assets/theme.js"
          
      - name: Auto Minify Css
        if: contains(needs.check_change.outputs.list_files, 'theme.css')
        uses: nizarmah/auto-minify@v2.1
        with: 
          directory: "assets/theme.css"

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
  deploy_preview:
    runs-on: ubuntu-latest
    name: 'Deploy Preview'
    needs: minified
    if: ${{ always() }} 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Shopify Theme Deploy Previews
        if: github.event.action != 'closed'
        uses: wyugen/shopify-theme-action@v1
        with:
          SHOPIFY_STORE: ${{secrets.DP_SHOPIFY_STORE}}
          SHOPIFY_APP_PW: ${{secrets.DP_SHOPIFY_APP_PW}}
          SHOPIFY_API_KEY: ${{secrets.DP_SHOPIFY_API_KEY}}
          github-token: ${{secrets.GITHUB_TOKEN}}
          CI: 1
          SHOPIFY_SHOP: ${{secrets.DP_SHOPIFY_STORE}}
          SHOPIFY_PASSWORD: ${{secrets.DP_SHOPIFY_APP_PW}}
