name: Auto minified JS, CSS and Deploy Preview
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:

  deploy_preview:
    runs-on: ubuntu-latest
    name: 'Deploy Preview'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup
        run: 
          sudo gem install shopify-cli #Install shopify-cli
      - name: Set env
        run: |
          echo "CI=1" >> $GITHUB_ENV
          echo "SHOPIFY_SHOP=${{secrets.DP_SHOPIFY_STORE}}" >> $GITHUB_ENV
          echo "SHOPIFY_PASSWORD=${{secrets.DP_SHOPIFY_APP_PW}}" >> $GITHUB_ENV
          

          
#       - name: Set the value
#         id: step_one
#         run: |
#           echo 'versionS<<EOF' >> $GITHUB_ENV
#           shopify version >> $GITHUB_ENV
#           echo 'EOF' >> $GITHUB_ENV

      - name: Test2
        run: |
          shopify login [--store ${{env.SHOPIFY_SHOP}}]
          shopify theme push --development 
          
          echo 'themeCreate<<EOF' >> $GITHUB_ENV
          shopify theme push --development --json  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
      - name: Test22
        run: 
          echo ${{github.event.pull_request.number}}

          
#       - name: fetch the json value
#         run: |
#            githubjson=`cat ${{env.themeCreate}}`
#            echo $githubjson
      - name: logout
        run: shopify logout
          

       
        

      
        
