name: Workflow pull_request
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
jobs:
  minified:
    - name: 'Auto minified JS and CSS'
      uses: ./.github/workflows/minified
      with:
          types_PR: ${{ github.event.action }}

  deploy_preview:
    - name: Deploy Preview
      uses: ./.github/workflows/deploy_preview
      with:
          types_PR: ${{ github.event.action }}
          number_PR: ${{ github.event.pull_request.number }}
          DP_SHOPIFY_STORE: ${{ secrets.DP_SHOPIFY_STORE }}
          DP_SHOPIFY_APP_PW: ${{ secrets.DP_SHOPIFY_APP_PW }}

        