name: Workflow pull request
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
jobs:
   update_deploy_preview:
    name: 'Update Deploy Preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: ./.github/workflows/minified2
  
        
